// src/components/react/Counter.tsx
import { useState } from 'react'

/** A counter written with React */
export function Counter({ children }) {
  const [count, setCount] = useState(0)
  const add = () => setCount((i) => i + 1)
  const subtract = () => setCount((i) => i - 1)

  return (
    <>
      <div className='counter'>
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div className='counter-message'>{children}</div>
    </>
  )
}

// src/components/svelte/Counter.svelte
<!-- @component
A counter written with Svelte (Svelte 5)
-->
<script lang="ts">
	let { children } = $props();
	let count = $state(0);

	function add() {
		count += 1;
	}

	function subtract() {
		count -= 1;
	}
</script>

<div class="counter">
	<button onclick={subtract}>-</button>
	<pre>{count}</pre>
	<button onclick={add}>+</button>
</div>
<div class="counter-message">
	{@render children?.()}
</div>
